### ISSUE TITLE
两个小建议

### ISSUE THREAD

**Issue by CreeperAWA** [KiyanYang/DotVast.HashTool.WinUI#40]
### 问题

我的电脑C盘快满了，希望可以自定义安装位置

### 解决方案

增加填写安装路径的地方

**Comment by KiyanYang** [comment]
`msix` 的默认安装位置由 Windows 设计为 `C:\Program Files\WindowsApps`，参考 [Understanding how packaged desktop apps run on Windows - Installation](https://learn.microsoft.com/windows/msix/desktop/desktop-to-uwp-behind-the-scenes#installation)。

有两种途径将软件位置变更（相关命令参考 [Windows PowerShell cmdlets for AppX](https://learn.microsoft.com/powershell/module/appx/?view=windowsserver2022-ps)）：

- 你可以在其他盘创建新的 `PackageVolume`，并将其设为默认的 `PackageVolume`，然后安装软件。
- 你可以在其他盘创建新的 `PackageVolume`，无需设置为默认，安装软件后（此时应在默认的C盘），将软件移动至该 `PackageVolume`。
