### ISSUE TITLE
增强计算效率

### ISSUE THREAD

**Issue by vicenteyu** [KiyanYang/DotVast.HashTool.WinUI#42]
### 问题

![image](https://github.com/KiyanYang/DotVast.HashTool.WinUI/assets/1539280/169d2a7e-8b81-4d24-a4a7-0c61c66d2e3e)
从资源上看，占用非常小，不会对设备额外许多负担。
从效率上看，感觉会比其他哈希工具计算稍慢一些。

### 解决方案

希望能增加一个选项，可以自主选择是否允许以充分使用设备资源的方式，用来提高计算效率。非常感谢提供这么优秀的工具。

**Comment by vicenteyu** [comment]
是自己编译的。出于什么原因考虑 限制 dev 版本的，方便说一下吗？或者提供一下解除的方法？

**Comment by KiyanYang** [comment]
因为需要方便地观察进度条等计算过程中的UI变化，这种限制仅在 `Debug` 模式下生效，切换到 `Release` 模式下编译就是正常的版本了。

**Comment by vicenteyu** [comment]
明白了，感谢解惑！
