### ISSUE TITLE
打算 提供绿色安装包不?

### ISSUE THREAD

**Issue by GmavionR** [KiyanYang/DotVast.HashTool.WinUI#43]
### Check

- [X] Make sure to search for existing [issues](https://github.com/KiyanYang/DotVast.HashTool.WinUI/issues) before filing a new one!
- [X] This bug can be reproduced in the latest version.

### Bug

d

### Steps to reproduce

d

### Expected Behavior

d

### Environment

```Markdown
- App Version: v0.5.0
- OS  Version: Windows 11 22H2 (22621.1413)
d
```

**Comment by KiyanYang** [comment]
没有此计划
